### ISSUE TITLE
Not Working on build 23H2 (22631.2861)

### ISSUE THREAD

**Issue by WildByDesign** [LesFerch/OldExplorer#1]
I hadn't tested OldExplorer for a few months now. However, when I tested the latest version (1.2.2) today on 23H2 (22631.2861), it did not work at all.

I also tried an older version of OldExplorer that used to work for me (1.0.4) on previous versions of Windows 11. But it did not work either.

**From System Informer:**
```
8:51:16 AM 12/27/2023, Process created: OldExplorer.exe (5628) started by cmd.exe (1412)
8:51:18 AM 12/27/2023, Process terminated: OldExplorer.exe (5628); exit status 0
```
So it did seem to execute without crashing. It just did not launch an Explorer window or anything.

**Comment by LesFerch** [comment]
I tested with 22631.2861 and didn't have any problem. What happens when you run **`control admintools`** from the Run box or a Cmd prompt?

**Comment by WildByDesign** [comment]
`control admintools` works as expected. That’s why I am not sure what could be failing. There is no antivirus or anything to get in the way.

OldExplorer does execute. It does close its own process after which I assume is expected. It just doesn’t do anything with explorer.

I may try again later with ProcMon or something else to get more info.

**Comment by WildByDesign** [comment]
I have some other tools also to log all command lines executed to ensure that that part is occurring.

**Comment by LesFerch** [comment]
I'd load up Visual Studio Community, download and open the source code, change the output type from "Windows application" to "Console application" and then press Ctrl-F5 to run and keep the console open. Hopefully that will display some error message.

**Comment by WildByDesign** [comment]
Each time that I run it, either from cmd or otherwise, I get the following in Event Log:

```
Unable to start a DCOM Server: {06622D85-6856-4460-8DE1-A81921B41C4B}. The error:
"2147943140"
Happened while starting this command:
C:\WINDOWS\system32\DllHost.exe /Processid:{06622D85-6856-4460-8DE1-A81921B41C4B}
```
Later in the day when I have more time, I will check some command line logger tool and I will also try your suggestion with Visual Studio Community.

But for now, anyway, that error in the event log is reproducible 100% of the time when I try to start OldExplorer.

**Comment by LesFerch** [comment]
Searching that error points to doing an in-place repair. Maybe there's a a more precision fix, but at least an in-place repair is non-destructive.

https://www.elevenforum.com/t/repair-install-windows-11-with-an-in-place-upgrade.418/

**Comment by WildByDesign** [comment]
Thanks Les. So far I have run the following usual commands:

```
sfc /scannow
DISM /online /cleanup-image /checkhealth
DISM /online /cleanup-image /scanhealth
DISM /online /cleanup-image /restorehealth
```

They all ran successfully and found no issues. I will likely end up doing a Repair Install or just do a Clean Install but wont have time to do that for a few weeks.

I will close this issue since this seems to be an issue that is specific to my machine. Thank you for all of the work that you have done and shared with the community. Especially with WinSetView because that fixed a few issues that Microsoft had created a while back. Cheers!
