### ISSUE TITLE
False positive?

### ISSUE THREAD

**Issue by IainP** [LesFerch/OldExplorer#2]
Not so much an issue with the program (thank you for it, I hate the new Win11 Explorer!), but Windows Security is picking it up as containing:

Trojan:Win32/Bearfoos.A!ml
This program is dangerous and executes commands from an attacker.

After manual scans with other antivirus packages, I'm gairly certain this is a false positive. Just wanted to let yoiu know.

**Comment by LesFerch** [comment]
It's a false positive. Try clearing your Defender history using [this](https://lesferch.github.io/ClearDefenderHistory/). Then click "Check for Updates" within Defender (not Windows Updates in general).

**Comment by LesFerch** [comment]
Also note that you can use [SwitchExplorer](https://lesferch.github.io/SwitchExplorer/) to set the Windows 10 Explorer as your default. That's also an option in [WinSetView](https://lesferch.github.io/WinSetView/).

**Comment by IainP** [comment]
Thanks for the Defender advice. I'll sort that now. I had looked at SwitchExplorer, but it's the Details Pain (pun intended) which is one of my main annoyances, so it's the full OldExplorer experience for me! Thank you for your work on this!
