### ISSUE TITLE
Shortcuts wont work 2.1.0

### ISSUE THREAD

**Issue by Ulfenknulfen** [LesFerch/OldExplorer#4]
Hi!

For me does shortcuts "oldexplorer.exe C:\Downloads" or "oldexplorer.exe Downloads" not work.
oldexplorer opens ever in folder "Systemsteuerung\Alle Systemsteuerungselemente\Öffentlich"

best regards
Paddy

**Comment by LesFerch** [comment]
I see. The start location argument always fails when the system language is not English. I'll look into it. Thanks for letting me know.

**Comment by Ulfenknulfen** [comment]
if it helps:
it was ok in 1.2.2.0

**Comment by LesFerch** [comment]
Yeah, that was very different. Version 1.x copy and pasted the path. Version 2.x uses the .navigate function. Working on it...

**Comment by LesFerch** [comment]
The problem is that I'm looking for a "File Explorer" window. That has to be localized or generalized as a cabinetclass window. I should have a moment to fix it later today or tomorrow.

**Comment by LesFerch** [comment]
2.1.1 is now available. It should work correctly with the system language set to any language.

**Comment by Ulfenknulfen** [comment]
Hi :-)

It's workking now. Thanks a lot for this helpfull tool!

best regards
Paddy
