### ISSUE TITLE
Won't run after a certain length of time

### ISSUE THREAD

**Issue by F-101B** [LesFerch/OldExplorer#7]
I can't seem to be able to use the program after a certain length of time. Clicking on the exe on the desktop or on the taskbar will show the blue loading circle for a moment, and then nothing will happen. This includes opening new tabs with it when one is already open. The solution I've found for the moment is to always open one tab of it on startup, which does remain working even when opening new ones won't. This on a few days old system running Win11 23H2 and now 24H2. I may just not be using this properly, as I'm computer savvy only up to a point. 

I appreciate that you created this; as a photographer, I've been using the metadata in the right pane to organize things for 15 years now. I can't figure out why they got rid of it.

**Comment by LesFerch** [comment]
I haven't heard of an issue like that before.

By "tabs" I assume you mean a taskbar item. Is that correct?

As a test, when it's stuck, see if you can open the Control Panel, either by clicking its icon or by opening the Run box and entering `control` or `control.exe`. OldExplorer opens the Windows 10 Explorer via the Control Panel mechanism, so it will interesting to see if Control Panel also doesn't open.

I would also try a test with a different local account (make it an administrator) to see if it's a system-side problem or something specific to your user profile. You can find instructions for creating a local account [here](https://www.elevenforum.com/t/add-local-user-account-in-windows-11.590/).

Although I don't think it will make a difference, I was wondering if your default Explorer is the Windows 11 version or the Windows 10 version? That is, have you used [SwitchExplorer](https://lesferch.github.io/SwitchExplorer/) or any other tool change the default?

I assume you don't have any Explorer mod program installed such as ExplorerPatcher, StartAllBack, WindHawk, or QTTabBar. There are no known issues with any of those, but it's always good to know what's involved when things aren't working right.

**Comment by F-101B** [comment]
I am using OpenShell, if that makes any difference. I am using the base Win11 explorer. Control in the Run box still opens as normal. I do mean a taskbar item, sorry that wasn't clear.

**Comment by LesFerch** [comment]
OK, thanks. Try this command in the Run box next time it's stuck:

`shell:::{26EE0668-A00A-44D7-9371-BEB064C98683}\0\::{4336A54D-038B-4685-AB02-99BB52D3FB8B}`

That's the same command OldExplorer uses to open the Windows 10 Explorer. It should open the Windows 10 Explorer to the Public folder.

**Comment by F-101B** [comment]
I was slightly incorrect yesterday, as I hadn't fully installed 24H2. However, so far today, with the update fully installed, this problem has yet to recur. If it does, I will try the command listed.

**Comment by LesFerch** [comment]
Excellent! I'll close this out then. You can still reply should the problem recur.
